version: '3'
networks:
  web:
    external:
      name: web
services:
  quasar:
    build: .
    container_name: quasar
    ports: 
      - "8002:8080"
    volumes: 
      - .:/home/node/app:rw
    labels:
    - "traefik.enable=true"
    - "traefik.backend=quasar"
    - "traefik.frontend.rule=Host:app.suptapee.com"
    - "traefik.docker.network=web"
    - "traefik.port=8080"
    networks:
    - "web"
    restart: "no"
    command: sh
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
